/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalExam_TRANVOANHTU_26211229825;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FormHinhHoc extends javax.swing.JFrame {
    DefaultTableModel dtm = new DefaultTableModel();
        MangHinh x = new MangHinh();
    /**
     * Creates new form FormHinhHoc
     */
    public FormHinhHoc() {
        initComponents();
        dtm.setColumnIdentifiers(new Object[]{"STT","LOẠI HÌNH ","","","","DIỆN TÍCH"});
        tblHienThi.setModel(dtm);
        txtB.setEnabled(false);
        txtC.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtHT = new javax.swing.JRadioButton();
        rbtHCN = new javax.swing.JRadioButton();
        rbtHHCN = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnDocFiile = new javax.swing.JButton();
        btnXuatFiile = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnMax = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORM HINH HOC");

        buttonGroup1.add(rbtHT);
        rbtHT.setText("Hình Tròn");
        rbtHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHTActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtHCN);
        rbtHCN.setText("Hình Chữ Nhật");
        rbtHCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHCNActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtHHCN);
        rbtHHCN.setText("Hình Hộp Chữ Nhật");
        rbtHHCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHHCNActionPerformed(evt);
            }
        });

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHienThi);

        lblTitle.setText("MỜI NHẬP BÁN KÍNH CỦA HÌNH TRÒN");

        btnDocFiile.setText("ĐỌC FILE");
        btnDocFiile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFiileActionPerformed(evt);
            }
        });

        btnXuatFiile.setText("XUẤT FILE");
        btnXuatFiile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFiileActionPerformed(evt);
            }
        });

        btnSapXep.setText("SẮP XẾP");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        btnMax.setText("MAX HCN");
        btnMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxActionPerformed(evt);
            }
        });

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtHT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rbtHCN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rbtHHCN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(txtB, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtA, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXuatFiile, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(btnDocFiile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMax, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtHT)
                    .addComponent(rbtHCN)
                    .addComponent(rbtHHCN))
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocFiile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatFiile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMax, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHTActionPerformed
        // TODO add your handling code here:
        txtB.setEnabled(false);
        txtC.setEnabled(false);
    }//GEN-LAST:event_rbtHTActionPerformed

    private void rbtHCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHCNActionPerformed
        // TODO add your handling code here:
        lblTitle.setText("MỜI NHẬP 2 CẠNH CỦA HÌNH CHỮ NHẬT");
        txtB.setEnabled(true);
    }//GEN-LAST:event_rbtHCNActionPerformed

    private void rbtHHCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHHCNActionPerformed
        // TODO add your handling code here:
        lblTitle.setText("MỜI NHẬP 2 CẠNH VÀ CHIỀU CAO CỦA HÌNH HỘP CHỮ NHẬT");
        txtB.setEnabled(true);
        txtC.setEnabled(true);
    }//GEN-LAST:event_rbtHHCNActionPerformed
    public void napDuLieuVaoBang(ArrayList <HinhTron>x){
        dtm.setRowCount(0);
        int dem=0;
        for(HinhTron y:x){
            if(y instanceof HinhChuNhat){
                dtm.addRow(new Object[]{dem,y.getName(),((HinhChuNhat) y).getCanh2(),((HinhChuNhat) y).getCanh1(),"",y.TinhDienTich()});
            }else if (y instanceof HiinhHopChuNhat) {
                dtm.addRow(new Object[]{dem,y.getName(),((HiinhHopChuNhat) y).getCanh1(),((HiinhHopChuNhat) y).getCanh2(),((HiinhHopChuNhat) y).getChieucao(),y.TinhDienTich()});
            }else{
                dtm.addRow(new Object[]{dem,y.getName(),y.getBanKinh(),"","",y.TinhDienTich()});
            }
            dem++;
        }
    }
    private void btnDocFiileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFiileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        String tenFile = fc.getSelectedFile().getPath();
        x.DocFile(tenFile);
        napDuLieuVaoBang(x.getList());
        JOptionPane.showMessageDialog(null,"ĐỌC FILE THÀNH CÔNG");
        btnDocFiile.setEnabled(false);
    }//GEN-LAST:event_btnDocFiileActionPerformed

    private void btnXuatFiileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFiileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(null);
        String tenFile = fc.getSelectedFile().getPath();
        x.XuatFile(tenFile, x.getList());
        JOptionPane.showMessageDialog(null,"XUẤT FILE THÀNH CÔNG");
        btnXuatFiile.setEnabled(false);
    }//GEN-LAST:event_btnXuatFiileActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
         if(x.getList().size()==0){
             JOptionPane.showMessageDialog(null,"VUI LÒNG THÊM DỮ LIỆU VÀO BẢNG");
        }else{
            x.SxTangDan();
             napDuLieuVaoBang(x.getList());
         }
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxActionPerformed
        // TODO add your handling code here:
        if(x.getList().size()==0){
             JOptionPane.showMessageDialog(null,"VUI LÒNG THÊM DỮ LIỆU VÀO BẢNG");
        }else{
             JOptionPane.showMessageDialog(null,x.maxDienTich());
        }
    }//GEN-LAST:event_btnMaxActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        HinhTron y = null;
        double a,b,c;
        if(txtA.getText()=="" ||txtB.getText()==""||txtC.getText()==""){
            JOptionPane.showMessageDialog(null,"VUI LÒNG NHẬP DỮ LIỆU");
        }else{
            if(rbtHT.isSelected()){
                a= Double.parseDouble(txtA.getText());
                y = new HinhTron(a);
            }else if (rbtHCN.isSelected()){
                a= Double.parseDouble(txtA.getText());
                b= Double.parseDouble(txtB.getText());
                y = new HinhChuNhat(a,b);
            }else{
                a= Double.parseDouble(txtA.getText());
                b= Double.parseDouble(txtB.getText());
                c= Double.parseDouble(txtC.getText());
                y=new HiinhHopChuNhat(a,b,c);
            }
        }
        if(x.themMoi(y)==false){
           JOptionPane.showMessageDialog(null, "HÌNH ĐÃ BỊ TRÙNG");
        }else{
            JOptionPane.showMessageDialog(null,y);
            napDuLieuVaoBang(x.getList());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHinhHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHinhHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocFiile;
    private javax.swing.JButton btnMax;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXuatFiile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtHCN;
    private javax.swing.JRadioButton rbtHHCN;
    private javax.swing.JRadioButton rbtHT;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
